server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql:///leyou?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: 192.168.28.131
  rabbitmq:
    host: 192.168.28.131
    virtual-host: /leyou
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka
  instance:
    lease-renewal-interval-in-seconds: 5  #指定心跳时间
    lease-expiration-duration-in-seconds: 15 #指定过期时间

mybatis:
  type-aliases-package: com.leyou.user.pojo