server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.28.131
    virtual-host: /leyou
    username: leyou
    password: leyou
leyou:
  sms:
    accessKeyId:  # AccessKeyId
    accessKeySecret:  # AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_187591516 # 模板名称
